// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQyDyUnDHCLDrfQ2worBWChtcsyhJpkd8',
    appId: '1:153668122379:web:c7f692ba34b8285043140e',
    messagingSenderId: '153668122379',
    projectId: 'lab6-fcm',
    authDomain: 'lab6-fcm.firebaseapp.com',
    storageBucket: 'lab6-fcm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT1za3FIExMwK1x0C1vd0kFEu6fGJEJys',
    appId: '1:153668122379:android:9191287e51bce93a43140e',
    messagingSenderId: '153668122379',
    projectId: 'lab6-fcm',
    storageBucket: 'lab6-fcm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3RR54TkW7qspYaUTWZd930kdPrvEYaV8',
    appId: '1:153668122379:ios:50c7d7389a65c5c743140e',
    messagingSenderId: '153668122379',
    projectId: 'lab6-fcm',
    storageBucket: 'lab6-fcm.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationsFcm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3RR54TkW7qspYaUTWZd930kdPrvEYaV8',
    appId: '1:153668122379:ios:50c7d7389a65c5c743140e',
    messagingSenderId: '153668122379',
    projectId: 'lab6-fcm',
    storageBucket: 'lab6-fcm.firebasestorage.app',
    iosBundleId: 'com.example.pushNotificationsFcm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQyDyUnDHCLDrfQ2worBWChtcsyhJpkd8',
    appId: '1:153668122379:web:4c0aa7550570f00943140e',
    messagingSenderId: '153668122379',
    projectId: 'lab6-fcm',
    authDomain: 'lab6-fcm.firebaseapp.com',
    storageBucket: 'lab6-fcm.firebasestorage.app',
  );
}
